# Generated by Django 3.2 on 2023-10-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='confirmation_code',
            field=models.CharField(blank=True, default='8D3iKs', max_length=30),
        ),
    ]
