# Generated by Django 3.2 on 2023-10-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
