# Generated by Django 3.2 on 2023-10-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_title_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='rating',
            field=models.PositiveIntegerField(default=None, verbose_name='Рейтинг'),
        ),
    ]
